# Generated by Django 5.0.3 on 2024-05-14 11:44

import my_site.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(null=True, storage=my_site.storage_backends.MediaStorage, upload_to='posts'),
        ),
    ]
