# Generated by Django 5.0.3 on 2024-06-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
